import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import Footer from "@/components/Footer";
import Dashbody from "@/components/Dashbody";
import Consultancy from "@/components/Services";
import { ThemeProvider } from "@/components/theme-provider";
import Services from "@/components/Services";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MenstruEase",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
      <body>
        <HeaderTop/>
        <ThemeProvider/>
        <Dashbody/>
        <Services/>
        <Footer/>
      </body>
  );
}
